-- Eliminar tablas al ejecutar
DROP TABLE IF EXISTS EMPLEADOS;
DROP TABLE IF EXISTS DEPARTAMENTOS;

-- Creacion de tablas
CREATE TABLE IF NOT EXISTS DEPARTAMENTOS
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre TEXT NOT NULL,
    presupuesto DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLEADOS
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    departamento_id BIGINT NOT NULL REFERENCES DEPARTAMENTOS (id)
);

-- DATOS INICIALES

INSERT INTO DEPARTAMENTOS (nombre, presupuesto)
VALUES ('PSP', 200.0);